# Generated by Django 3.0.7 on 2020-06-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('valor', models.FloatField()),
                ('data_transacao', models.DateTimeField(verbose_name='Data da Transação')),
                ('recorrencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pago', models.CharField(choices=[('nao_pago', 'Não Pago'), ('pago', 'Pago')], max_length=8)),
                ('tipo_transacao', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=7)),
            ],
            options={
                'db_table': 'transacao',
            },
        ),
    ]
