# Generated by Django 3.0.7 on 2020-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='recorrencia',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
