# Generated by Django 3.0.7 on 2020-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200623_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='pago',
            field=models.CharField(choices=[('nao_pago', 'Não Pago'), ('pago', 'Pago')], max_length=8),
        ),
    ]
