# Generated by Django 3.0.7 on 2020-06-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200625_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='pago',
            field=models.CharField(choices=[('pago', 'Pago'), ('nao_pago', 'Não Pago')], max_length=8),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=7),
        ),
    ]
