# Generated by Django 3.0.7 on 2020-06-25 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200625_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacao',
            name='pago',
            field=models.CharField(choices=[('nao_pago', 'Não Pago'), ('pago', 'Pago')], max_length=8),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=7),
        ),
    ]
