# Generated by Django 3.0.7 on 2020-06-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200625_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='pago',
            field=models.CharField(choices=[('nao_pago', 'Não Pago'), ('pago', 'Pago')], max_length=8),
        ),
    ]
