# Generated by Django 3.0.7 on 2020-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200625_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='pago',
            field=models.CharField(choices=[('pago', 'Pago'), ('nao_pago', 'Não Pago')], max_length=8),
        ),
    ]
