# Generated by Django 3.0.7 on 2020-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200625_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=7),
        ),
    ]
