# Generated by Django 3.0.7 on 2020-06-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200626_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=7),
        ),
    ]
